"""make_quiz_student_id_nullable_and_add_deadline

Revision ID: e16679b3e9b7
Revises: add_perf_indexes_001
Create Date: 2026-07-13 20:13:00.426874+07:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e16679b3e9b7'
down_revision: Union[str, None] = 'add_perf_indexes_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.alter_column('quizzes', 'student_id',
               existing_type=sa.BigInteger(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'student_id',
               existing_type=sa.BigInteger(),
               nullable=False)
    op.drop_column('quizzes', 'deadline')
    # ### end Alembic commands ###
